version: '3'
services:
  mongo:
    container_name: "mongo-container"
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/bd
    ports:
      - "27017:27017"
  api:
    container_name: "api-container"
    build: .
    image: house-renting-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/house-renting-api/dist
      - ./package.json:/usr/srsc/house-renting-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
